# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'demo/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Max: 100
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/Lambda:
  Enabled: false
